version: '3.8'

services:

  service_main_crawler:
    container_name: service_main_crawler
    build:
      context: ./service_main_crawler
    working_dir: /app
    volumes:
      - ./service_main_crawler/src:/app/src   # Mount the project directory
    depends_on:
      - rabbitmq  
    networks:
      - car_crawler_network

  service_detail_crawler:
    container_name: service_detail_crawler
    build:
      context: ./service_detail_crawler
    working_dir: /app
    volumes:
      - ./service_detail_crawler/src:/app/src   # Mount the project directory
    depends_on:
      - rabbitmq  
    networks:
      - car_crawler_network
    command: ["python", "src/app.py"]

  service_main_saver:
    container_name: service_main_saver
    build:
      context: ./service_main_saver
    working_dir: /app
    volumes:
      - ./service_main_saver/src:/app/src   # Mount the project directory
      - ./service_main_saver/cars.db:/app/cars.db
    depends_on:
      - rabbitmq  
    networks:
      - car_crawler_network
    command: ["python", "src/app.py"]

  service_detail_saver:
    container_name: service_detail_saver
    build:
      context: ./service_detail_saver
    working_dir: /app
    volumes:
      - ./service_detail_saver/src:/app/src   # Mount the project directory
      - ./service_detail_saver/cars_detail.db:/app/cars_detail.db
    depends_on:
      - rabbitmq  
    networks:
      - car_crawler_network
    command: ["python", "src/app.py"]

  service_image_saver:
    container_name: service_image_saver
    build:
      context: ./service_image_saver
    working_dir: /app
    volumes:
      - ./service_image_saver/src:/app/src   # Mount the project directory
      - ./service_image_saver/images.db:/app/images.db
    depends_on:
      - rabbitmq  
    networks:
      - car_crawler_network
    command: ["python", "src/app.py"]

  rabbitmq:
    container_name: rabbitmq_service
    hostname: 'rabbitmq_python' #Biar datanya ga ilang perlu ditambahin ini
    image: rabbitmq:3-management  # RabbitMQ image with management plugin
    ports:
      - "5672:5672"       # Default port for RabbitMQ
      - "15672:15672"     # Default port for RabbitMQ Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - car_crawler_network

volumes:
  rabbitmq_data:
    driver: local
networks:
  car_crawler_network:
    driver: bridge